// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pijqlyzuavxgxcqblykx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpanFseXp1YXZ4Z3hjcWJseWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMDI3NzgsImV4cCI6MjA2OTU3ODc3OH0.QkSeXVfJI2muDUj9RLIfCxZRYT8VugkuO6zfZv5dpPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});